version: '3.7'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./compose/production/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files/static:/srv/static
      - ./files/media:/srv/media
    depends_on:
      - daphne

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data/
    env_file:
      - compose/production/.env

  redis:
    image: redis

  daphne:
    image: matman_daphne
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start-daphne.sh
    depends_on:
      - redis
      - db
    env_file:
      - compose/production/.env
    volumes:
      - ./matman:/app
      - ./files/static:/app/files/static
      - ./files/media:/app/files/media

  # https://testdriven.io/courses/django-celery/docker/

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: matman_celery_worker
    command: /start-celeryworker.sh
    depends_on:
      - redis
      - db
      - daphne
    env_file:
      - compose/production/.env
    volumes:
      - ./matman:/app
      - ./files/static:/app/files/static
      - ./files/media:/app/files/media

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: matman_celery_beat
    command: /start-celerybeat.sh
    depends_on:
      - redis
      - db
      - daphne
    env_file:
      - compose/production/.env
    volumes:
      - ./matman:/app
      - ./files/static:/app/files/static
      - ./files/media:/app/files/media

  flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: matman_flower
    command: /start-flower.sh
    depends_on:
      - redis
      - db
      - celery_beat
      - celery_worker
    env_file:
      - compose/production/.env
    volumes:
      - ./matman:/app
    ports:
      - 5555:5555
