version: '3.7'

services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./compose/production/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
      - ./files/static:/srv/static
      - ./files/media:/srv/media

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data/
    env_file:
      - compose/production/.env

  redis:
    image: redis

  daphne:
    image: matman_daphne
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start-daphne.sh
    depends_on:
      - redis
      - db
    env_file:
      - compose/production/.env
    volumes:
      - ./matman:/app
      - ./files/static:/files/static
      - ./files/media:/files/media

  # https://testdriven.io/courses/django-celery/docker/

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: matman_celery_worker
    command: /start-celeryworker.sh
    depends_on:
      - redis
      - db
    env_file:
      - compose/production/.env
    volumes:
      - ./matman:/app
      - ./files/static:/files/static
      - ./files/media:/files/media

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: matman_celery_beat
    command: /start-celerybeat.sh
    depends_on:
      - redis
      - db
    env_file:
      - compose/production/.env
    volumes:
      - ./matman:/app
      - ./files/static:/files/static
      - ./files/media:/files/media

  flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: matman_flower
    command: /start-flower.sh
    depends_on:
      - redis
      - db
    env_file:
      - compose/production/.env
    volumes:
      - ./matman:/app
    ports:
      - 5555:5555

volumes:
  caddy_data:
  caddy_config:
