# Generated by Django 4.0.5 on 2022-08-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='_id_counter',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='identifier',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
