# Generated by Django 4.0.5 on 2022-08-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matman', '0005_alter_userprofile_default_scheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='department',
            new_name='scheme',
        ),
    ]
