# Generated by Django 4.0.5 on 2022-08-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matman', '0006_rename_department_material_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='slug',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='prefix',
            field=models.CharField(max_length=10),
        ),
    ]
