# Generated by Django 4.0.5 on 2022-09-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matman', '0007_remove_scheme_slug_alter_scheme_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='usage_location',
            field=models.CharField(default='nowhere', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
