# Generated by Django 4.0.5 on 2022-09-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matman', '0008_borrow_usage_location_alter_scheme_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='matman.material')),
            ],
        ),
    ]
