# Generated by Django 4.0.5 on 2022-09-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matman', '0009_materialpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpicture',
            name='file',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
