# Generated by Django 4.0.5 on 2022-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matman', '0012_materialpicture_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpicture',
            name='title',
            field=models.CharField(default='Title', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='descpription',
            field=models.CharField(default='no description', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialpicture',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
