# Generated by Django 4.1.7 on 2023-03-18 11:53

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from ..models import Scheme


def apply_migration(apps, schema_editor):
    scheme_admins = Group.objects.create(name='Scheme Admins')

    content_type = ContentType.objects.get_for_model(Scheme)
    scheme_admins.permissions.set(Permission.objects.filter(content_type=content_type,
                                                            codename__in=['add_scheme', 'change_scheme']))
    scheme_admins.save()


def revert_migration(apps, schema_editor):
    Group.objects.filter(name='Scheme Admins').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]