# Generated by Django 4.0.5 on 2022-06-24 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netaccess_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshpubkey',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sshpubkey',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 24, 14, 57, 55, 746996)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sshpubkey',
            name='expiration_date',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sshpubkey',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
