# Generated by Django 4.0.5 on 2022-06-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netaccess_users', '0003_permitopenrestriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshpubkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubkeys', to='netaccess_users.profile'),
        ),
    ]
