# Generated by Django 4.0.5 on 2022-06-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netaccess_users', '0004_alter_sshpubkey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshpubkey',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
