# Generated by Django 4.0.5 on 2022-06-25 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netaccess_users', '0005_sshpubkey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshpubkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubkeys', to=settings.AUTH_USER_MODEL),
        ),
    ]
