# Generated by Django 4.0.5 on 2022-06-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netaccess_users', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitopenrestriction',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sshpubkey',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
