# Generated by Django 4.0.5 on 2022-06-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netaccess_users', '0009_systempermissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allow_port_forwarding',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='allow_samba_access',
        ),
    ]
