# Generated by Django 4.0.5 on 2022-08-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netaccess_users', '0010_remove_profile_allow_port_forwarding_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
